### ISSUE TITLE
node_modules checked into package

### ISSUE THREAD

**Issue by msiebuhr** [sivy/node-statsd#14]
The directory `node_modules` shouldn't be in the repository (the package `mersenne` was added in f3796333b3ea43a5bc6bbdb550265fdc3cd69ca7). Ideally, it should be a dependency of the package.

(Or has the mersenne-package been hacked to work for node-statsd?)

**Comment by Dieterbe** [comment]
it was accidentially added in #12
I checked that the version in npm is the same and fixed it in 3fae6c28fb9ced559f74bf93e435879866b130b2 and 800f929f54cccc66e51e5ef15cb8b69a20e2e2f0
