### ISSUE TITLE
node-statsd needs a new maintainer

### ISSUE THREAD

**Issue by sivy** [sivy/node-statsd#15]
Hi folks:

This project needs a maintainer - I was the original author but I don't use node.js on a regular basis and my knowledge was never that deep. There are some great devs here, and I'm hoping one of you might like to take on the project.

@rcrowley, @lloyd, @mojodna, @msiebuhr, @salty-horse, @codefridge, @kastner ...

If one of you guys is interested in taking over maintainership, or knows someone who would be, get in touch and I'll hand over the reigns. Once we work out who (or group of whos) is going to take over, you can update the README with a note as to the new "canonical" repo, and give me a pull request, and I'll merge it here.

Thanks for participating and helping to make node-statsd a better tool than it was when I started! :-)

--Steve

**Comment by msiebuhr** [comment]
I'll happily take over (and roll my [node-statsd-client](https://github.com/msiebuhr/node-statsd-client) with this one; I mostly hacked mine together in order to fix a few technical annoyances.)

Anybody else?

**Comment by rafalio** [comment]
I don't want to take over, but I agree that someone needs to take over. The version on npm needs to be updated, the current one is from 307 days ago, and there have been changes.

**Comment by Dieterbe** [comment]
how about we just make the msiebuhr the new maintainer?  if the other invited people would actually respond, how would we even compare the candidates? this seems like a small enough project where enough people are watching it and trying to get involved on the issue tracker so I don't think it matters much who is the official maintainer.

**Comment by msiebuhr** [comment]
I must admit I have second thoughts. As this project seemed somewhat dead, I forged ahead with my own module, [statsd-client](/msiebuhr/node-statsd-client). The only feature missing, compared to this project, is sampling-support - otherwise, it has ephemeral socket(s), namespaces and a few other handy features.

All in all, I have trouble seeing the point in maintaining this in parallel...

**Comment by sethfitz** [comment]
I'm also using my own module--[node-metricsd](/mojodna/node-metricsd)--which also lacks sampling support, but has everything else (though it targets [metricsd](/mojodna/metricsd), a statsd-work-alike).

**Comment by Dieterbe** [comment]
then I volunteer.  I don't think starting new projects that can't be merged back is the right approach, especially if those new projects lack features that this one has. it makes the whole ecosystem more complicated

**Comment by sivy** [comment]
Hey Dieter,

I'd be glad for you to take this over. Email me @ steve@wallrazer.com and let's talk.

**Comment by Dieterbe** [comment]
for the time being, this is not a problem anymore.  I'm helping out @sivy with maintenance
