### ISSUE TITLE
update npm package

### ISSUE THREAD

**Issue by booo** [sivy/node-statsd#19]
Any plans to do so? I'm missing the gauge function for example.

Best regards

Philipp

**Comment by henryoswald** [comment]
bump!

**Comment by Dieterbe** [comment]
I would like to take care of this but last time I checked I didn't have npm publish permissions.  @sivy any updates? thanks!

**Comment by mattmonson** [comment]
+1

**Comment by sivy** [comment]
Deiter: what's your npm username?

On Mon, Sep 10, 2012 at 5:42 PM, Matt Monson notifications@github.comwrote:

> +1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sivy/node-statsd/issues/19#issuecomment-8443445.

## 

Steve Ivy
http://monkinetic.com // http://diso-project.org
This email is: [ ] bloggable [x] ask first [ ] private

**Comment by Dieterbe** [comment]
it's just 'dieter'

**Comment by sivy** [comment]
Done!  

## 

Steve Ivy
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by Dieterbe** [comment]
I just pushed a new version, 0.0.3 to npm. It doesn't show yet on https://npmjs.org/package/node-statsd , that seems to take a while. but `npm install node-statsd` yielded me the new version.

update: the webinterface updated after about an hour

**Comment by sivy** [comment]
Thanks Dieter!

On Wed, Sep 12, 2012 at 1:10 AM, Dieter Plaetinck
notifications@github.comwrote:

> I just pushed a new version, 0.0.3 to npm. It doesn't show yet on
> https://npmjs.org/package/node-statsd , that seems to take a while. but npm
> install node-statsd yielded me the new version.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sivy/node-statsd/issues/19#issuecomment-8485279.

## 

Steve Ivy
http://monkinetic.com // http://diso-project.org
This email is: [ ] bloggable [x] ask first [ ] private

**Comment by kaserf** [comment]
sorry if I re-use this old issue, but what are the plans to bring 0.0.4 to npm soon?

**Comment by devdazed** [comment]
I can take care of this it @Dieterbe and @sivy don't have time, but I do not yet have npm publish ability,

**Comment by sivy** [comment]
Russ, what's your npm username?

**Comment by devdazed** [comment]
devdazed

**Comment by kaserf** [comment]
thank you guys, pure awesomeness.

**Comment by sivy** [comment]
@devdazed Done.

**Comment by sivy** [comment]
Someone please push the latest - I don't have time today - and close this. Our poor users!

**Comment by devdazed** [comment]
ok, this has been published as 0.0.4.
