### ISSUE TITLE
Forked your work

### ISSUE THREAD

**Issue by dscape** [sivy/node-statsd#23]
Would be awesome to just merge it all in, but you seemed unresponsive to merge stuff and I think this was due.

If you feel like merging back, let me know, I can send a pull request and delete my fork from npm.

**Comment by dscape** [comment]
https://github.com/dscape/lynx

**Comment by Dieterbe** [comment]
Hi, I will gladly merge in good contributions, but the way to do that is opening pull requests.  you don't seem to have any pending pull request.

**Comment by Dieterbe** [comment]
uhm.. yeah... PR's are really the way to get stuff merged..
