### ISSUE TITLE
merging back with other clients?

### ISSUE THREAD

**Issue by jedi4ever** [sivy/node-statsd#27]
Any chance I help with merging with the other 4 modules I found?

https://github.com/msiebuhr/node-statsd-client
https://github.com/sivy/node-statsd
https://github.com/spreaker/nodejs-statsd-client
https://github.com/dscape/lynx

**Comment by Dieterbe** [comment]
msiebuhr purposely wants to maintain his own client; the last two in the list i'm not familiar with, is there anything specific from them that should be merged?

**Comment by devdazed** [comment]
I'm going to close this in a few days if there is no response as to what features should be included in this client.

**Comment by jedi4ever** [comment]
fwiw - here is a comparison list - https://gist.github.com/jedi4ever/6068660

I'm going for node-statsd :) Things you might want to add as a functionality:
- transformation function to pass to dynamically calculate the metric name
- ephemeral sockets
- socket timeout
- a mention to the express connect helper 
- cli command
- childs (ability to reuse connection with multiple prefix)

hope this is useful
