### ISSUE TITLE
Leaks file descriptors

### ISSUE THREAD

**Issue by tmm1** [sivy/node-statsd#3]
See https://github.com/msilvey/node-statsd/commit/0ade323fb52908c21e42d2e09f65786e5339e1d0, https://github.com/37signals/node-statsd/commit/d35ad6127e5cf88c0c859fa4f9e641cc31c8fe13 and other forks.

Additionally, one socket can be created upfront and re-used for the life of the process.

**Comment by tmm1** [comment]
See https://github.com/github/node-statsd/commit/f008117955ef5dac4c16245d7034693eb42c277c

**Comment by tmm1** [comment]
It appears the socket issue was fixed in #2. Can you merge the patch to re-use a socket and release a new version to npm?

**Comment by sivy** [comment]
Thanks! I'm going to take some time friday to do some maintenance on all my statsd clients. :-)

**Comment by tmm1** [comment]
Thanks for merging #4. Can you please push a new version to npm?

**Comment by sivy** [comment]
Fixed and pushed to npm. Thanks @tmm1.

**Comment by sivy** [comment]
http://search.npmjs.org/#/node-statsd

**Comment by tmm1** [comment]
Thanks!
