### ISSUE TITLE
errors when installing node-statds

### ISSUE THREAD

**Issue by Pomax** [sivy/node-statsd#33]
On the latest version, I'm getting the following errors when trying to `npm install node-statsd` (using node 0.10.20, npm 1.3.11)

```
npm WARN package.json jshint@0.9.1 No repository field.
npm WARN package.json toobusy@0.2.2 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm http GET https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
npm http 200 https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
npm WARN optional dep failed, continuing node-statsd@0.0.2
```

even though it fails the optional dep. no node-statsd dir exists in the ./node-modules dir after npm finishes

**Comment by devdazed** [comment]
Well from that output you aren't even installing this module, you are installing the module `https://github.com/downloads/lloyd/node-statsd/0509f85.tgz`

So if you have an issue with that module, I would put in issue in there.  To install this module, you can run `npm install node-statsd` and get the following output:

```
$ npm install node-statsd
npm http GET https://registry.npmjs.org/node-statsd
npm http 200 https://registry.npmjs.org/node-statsd
npm http GET https://registry.npmjs.org/node-statsd/-/node-statsd-0.0.7.tgz
npm http 200 https://registry.npmjs.org/node-statsd/-/node-statsd-0.0.7.tgz
node-statsd@0.0.7 node_modules/node-statsd
```

As you can see, we are on version 0.0.7 and the URL for this project is `https://github.com/sivy/node-statsd`, not the `lloyd` one that your output specifies.

**Comment by Pomax** [comment]
indeed. didn't realise npm would use package.json even for explicitly named packages, and someone had that alternate version indicated. removed it, retried, worked fine. Thanks for pointing it out!
