### ISSUE TITLE
Tag recent releases

### ISSUE THREAD

**Issue by strk** [sivy/node-statsd#35]
the npm registry knows about releases up to 0.0.7 but the latest published git tag os 0.0.2

**Comment by waisbrot** [comment]
And 0.0.7 is before tags were added, so grabbing the latest version is out of sync with the documentation.

**Comment by p2004a** [comment]
And histograms are missing in 0.0.7 too.

**Comment by Nevon** [comment]
This just bit me, as I tried to use `histograms` with the version installed from npm.

**Comment by longlho** [comment]
+1 for this. `histogram` just crapped out for me too

**Comment by devdazed** [comment]
Ok, just published the latest under 0.1.0.
